### ISSUE TITLE
wordpress-alpine-php: Provide a way for custom nginx config files

### ISSUE THREAD

**Issue by nphmuller** [Azure/app-service-quickstart-docker-images#179]
### This issue is for a:

- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

The apache based wordpress-alpine-php images allowed custom site rules per path/url via .htaccess files.
This for example allowed us to whitelist wp-admin for certain IP's.

I'm really happy with the performance improvments in the nginx based images. But .htaccess files not working are a really big downside for us. It would be great if a custom nginx config file could be provided without creating a custom Docker image (like .htaccess allowed us).

One way to accomplish this would be to check for example /home/site/nginx-conf.d/ for config files and use them automatically.

**Comment by nphmuller** [comment]
It’s probably a bit more complex than I initially suggested. The /home/site/nginx-conf.d/ solution would probably suffice for global configuration customizations. But if I also want to customize the site configuration (like in my example of white listing the wp-admin path) the original site configuration needs an include (example: https://serverfault.com/a/70796). This include would need to point a folder containing site customizations. Perhaps something like /home/site/nginx-site-conf.d/

Anyway, just giving you some food for thought @LeonZhang77 :)

**Comment by LeonZhang77** [comment]
just pushed image: appsvcorg/wordpress-alpine-php:0.7, could you please have a try? 
Readme: https://github.com/Azure/app-service-quickstart-docker-images/tree/master/wordpress-alpine-php/0.7 
## How to update config files of nginx
1. Go to "/etc/nginx", update config files as your wish. 
5. Reload by below cmd: 
```
/usr/sbin/nginx -s reload
```

**Comment by jstawski** [comment]
Would this survive a `Docker Restart`? I'm trying to modify the nginx.conf file to allow CORS of certain files and after restarting the web app in Azure, the equivalent of Docker Restart my conf file is set back to the original form

**Comment by LeonZhang77** [comment]
yes, this is by design. everything will be restored after restart except /home. 

good point, i will think what i can do.

**Comment by LeonZhang77** [comment]
@jstawski , appsvcorg/wordpress-alpine-php:0.7 is built and pushed again, please have a try. nginx conf files should not be overwrite by restart.
