### ISSUE TITLE
drupal-nginx-fpm: 0.44 php.ini for PHP 7.x is no longer allowed to use '#' as a comment

### ISSUE THREAD

**Issue by chrisjosephs** [Azure/app-service-quickstart-docker-images#185]
### This issue is for a: (mark with an `x`)

- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> The php.ini contains a comment that uses # instead of ; to start the comment line, which means that php rejects the configuration from the php.ini.  You can verify this by calling phpinfo(),  and see that upload_max_filesize for example is 2M rather than 20M as specified in the .ini.  This is because # is no longer supported as of php 7, so this would have been acceptable in php 5.x

### Any log messages given by the failure
> Does not throw an error, but phpinfo() will show default settings instead

### Expected/desired behavior
> upload_max_filesize for example is 20M rather than 2M as specified in the .ini, as with other settings in the .ini

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chrisjosephs** [comment]
I have fixed this in my fork: https://github.com/chrisjosephs/app-service-quickstart-docker-images/tree/master/drupal-nginx-fpm/0.44

**Comment by chrisjosephs** [comment]
Having fixed this however, this then reveals that the line in the php.ini referring to "extension=redis.so" is incorrect as php will throw warning: PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/redis.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/redis.so: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/redis.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/redis.so.so: No such file or directory)) in Unknown on line 0
So redis.so also needs locating properly (I could not find it in /usr/local/lib/php/extensions/no-debug-non-zts-20170718/ alongside xdebug.so or acpu.so(, or it will throw a warning every time php is invoked from the commandline.

**Comment by LeonZhang77** [comment]
thank you so much, I am trying...

this issue will be fixed in next version of appsvcorg/drupal-nginx-fpm

**Comment by LeonZhang77** [comment]
hi, Chris, 

built and pushed appsvcorg/drupal-nginx-fpm:0.46, i can see php memory is 512M in status report.

thanks again! You are really helpful.

-Leon
