### ISSUE TITLE
Add logrotate support

### ISSUE THREAD

**Issue by EricSten-MSFT** [Azure/app-service-quickstart-docker-images#191]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> Normal usage.  The logs grow to an unbounded size, which eventually causes site slowdown if logs ever grow \> 500MB in size.  This has been observed by customers with php-error.log files in excess of 500MB.

### Any log messages given by the failure
> None.  Lack of log rotation causes performance slowdown.

### Expected/desired behavior
> Speedy write to log files all the time.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LeonZhang77** [comment]
added log rotate into appsvcorg/nginx-fpm:php7.2.13.
added log rotate into appsvcorg/wordpress-alpine-php:0.7.
