### ISSUE TITLE
Unable to SSH into multi container Wordpress

### ISSUE THREAD

**Issue by simonbuerger** [Azure/app-service-quickstart-docker-images#280]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
Attempting to SSH via Azure webssh into quick start image for multi-container wordpress (appsvcorg/nginx-multi-container:0.1-wordpress-fpm) via docker-compose (with no changes to the given docker-compose template) doesn't work.

### Any log messages given by the failure
SSH CONNECTION CLOSE - Error: connect ECONNREFUSED 172.23.0.4:2222

### Expected/desired behavior
SSH connections should work out the box for Azure quickstart images

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LeonZhang77** [comment]
this is a know issue,  it related with azure platform.
