### ISSUE TITLE
Permalink settings added to wordpress-alpine-php 0.72 break ability for user to set in WP dashboard or functions.php in theme

### ISSUE THREAD

**Issue by fl-frontend** [Azure/app-service-quickstart-docker-images#286]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> Try setting permalinks in WP dashboard and they are overridden by settings from permalinks.txt that are added to wp-settings.php and reset to /%year%/%monthnum%/%day%/%postname%/ 
If permalink settings are included in a theme in functions.php or a  site-functionality plugin the setting in wp-settings.php causes a 500 error

### Any log messages given by the failure
>PHP Fatal error:  Cannot redeclare set_permalink() (previously declared in /home/site/wwwroot/wp-settings.php:507) in /home/site/wwwroot/wp-content/plugins/site-functionality/includes/post-types.php

### Expected/desired behavior
> Permalink settings should be able to be set via Wordpress dashboard or in functions.php as chosen by the user. wp-settings.php is a core Wordpress file that should not be modified as can cause unexpected behaviour.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LeonZhang77** [comment]
Some users in West Europe found this images will set customer permalink during deploy to azure, and it cause performance problem. That's why we set it in wp-settings.php by default. we have listed this as limitation in readme.md.

i am still looking for a way that needn't modify wp-settings.php, and it can make sure working normally in West Europe.

**Comment by LeonZhang77** [comment]
We remove these lines form wp-settings.
