### ISSUE TITLE
SSH missed

### ISSUE THREAD

**Issue by cool9brain** [Azure/app-service-quickstart-docker-images#311]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> Try to SSH to the container

### Any log messages given by the failure
>

docker file missing following step compared to version 0.46
# ssh
COPY sshd_config /etc/ssh/ 

### Expected/desired behavior
> SSH connection successful 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LeonZhang77** [comment]
Thanks for point out SSH issue of 0.5/0.51, I have fixed and re-pushed them. Please have a try again.

**Comment by cool9brain** [comment]
Thanks for the quick response. Yes it works fine now. I assume you will merge the changes
https://github.com/Azure/app-service-quickstart-docker-images/blob/master/drupal-nginx-fpm/0.51/Dockerfile
